### ISSUE TITLE
Task completion callback called too many times

### ISSUE THREAD

**Issue by ozgrozer** [BigstickCarpet/simplifyify#21]
I'm using Simplifyify with Gulp like that.

```js
gulp.task("simplifyify", function(done) {
  simplifyify("app/dev/js/*.js",
    {
      outfile: "app/prod/js/*.js",
      debug: true,
      minify: false
    })
    .on("end", function() {
      done();
    })
    .on("error", function(err) {
      done(err);
    });
});
```

If there is just one file in the source folder, Simplifyify works perfectly. But if there are two or more files in the source folder Simplifyify gives those errors.

```bash
'simplifyify' errored after 845 ms
[16:59:35] Error: task completion callback called too many times
    at finish (/path/electron/node_modules/orchestrator/lib/runTask.js:15:10)
    at cb (/path/electron/node_modules/orchestrator/lib/runTask.js:29:3)
    at EventEmitter.<anonymous> (/path/electron/gulpfile.js:62:4)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at Browserify.browserify.on (/path/electron/node_modules/simplifyify/lib/write-bundles.js:175:12)
    at emitNone (events.js:91:20)
    at Browserify.emit (events.js:188:7)
    at browserify.postProcessing.then (/path/electron/node_modules/simplifyify/lib/write-bundles.js:228:22)
```

I couldn't find a helpful answer. Any solution?

**Comment by BigstickCarpet** [comment]
Simplifyify just [propagates events from Browserify](https://github.com/BigstickCarpet/simplifyify/blob/25e261ec2fcad80158cbb5a4af4feb4dfe800f91/lib/write-bundles.js#L170-L182).  If you have multiple entry files, then there will be multiple Browserify instances propagating events, which is why any of the events can fire multiple times.  So, for example, if you have 5 entry files, then you'd need to handle the "end" event like this:

```javascript
    .on("end", function() {
        finished++;
        if (finished === 5) {
            done();
        }
    })
```

However, I think you'll agree that this is neither an elegant nor a straightforward solution.  Simplifyify should emit its own synthetic event when **all** of the bundles have finished building.  Then you could simply handle that event instead of the "end" event.

```javascript
    .on("finish", function() {
        done();
    })
```

**Comment by ozgrozer** [comment]
Both of them don't work with Gulp Watch.
